[package]
authors.workspace = true
categories.workspace = true
description = "Experimental no_std core parser and event writer for Eon"
edition.workspace = true
homepage.workspace = true
include.workspace = true
keywords.workspace = true
license.workspace = true
name = "eon_core"
publish = false
readme = "../../README.md"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lints]
workspace = true

[features]
default = []

[dependencies]

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
